### ISSUE TITLE
自动生成代码提示文件

### ISSUE THREAD

**Issue by tolking** [TDesignOteam/tdesign-api#51]
我注意到 tdesign 的 api 文档都是从这里自动生成的，理论上也可以从这里生成相关代码提示文件，然后像文档一样提交到各个组件库。

从这里生成代码提示文件或许是解决 [缺少代码提示相关问题](https://github.com/Tencent/tdesign-vue-next/issues/1617) 的最佳方案。

生成时仅需要统计并转换 api.json 中相关数据即可，当 api 变动后需要和文档一起被重新生成

**Comment by tolking** [comment]
我不清楚这样是否符合工作流程，有人能够给出建议吗？

**Comment by uyarn** [comment]
> 我不清楚这样是否符合工作流程，有人能够给出建议吗？

这个工具也有这样的功能 可以自动提PR到各个仓库 但是目前还不够完善 

另外代码提示的功能还是需要编辑器插件来辅助

**Comment by tolking** [comment]
对vue的代码提示 WebStorm 支持通过 [JetBrains/web-types](https://github.com/JetBrains/web-types) 实现

**Comment by uyarn** [comment]
> 对vue的代码提示 WebStorm 支持通过 [JetBrains/web-types](https://github.com/JetBrains/web-types) 实现

那这个确实可以从这边弄个脚本生成的 应该是这个issue https://github.com/Tencent/tdesign-vue-next/issues/1900

**Comment by tolking** [comment]
如果需要我可以完成解析 api.json 生成 web-types 相关代码，同时也可以包括适用于 vetur 提示的 tags.json、attributes.json

**Comment by uyarn** [comment]
> 如果需要我可以完成解析 api.json 生成 web-types 相关代码，同时也可以包括适用于 vetur 提示的 tags.json、attributes.json

欢迎👏🏻 可以做一下 然后提个PR

**Comment by chaishi** [comment]
API 工具支持过生成 vscode 提示文件，但是那个插件维护的不多，就停下了

**Comment by chaishi** [comment]
是完全可以自动生成相关提示文件的，只是需要知道输出的文件具体是什么格式，什么内容，实现起来都不麻烦
