### ISSUE TITLE
TDesign.db 每次冲突就丢失数据的问题

### ISSUE THREAD

**Issue by LeeJim** [TDesignOteam/tdesign-api#74]
每次冲突会自动丢掉 TDesign.db 的数据。
每次提交前，如果有其他人提交了，我的所有改动都要重新改一遍，很麻烦。
看看怎么解决下这个问题？

我有个想法：
- 将 TDesign.db 放在云端
- 考虑下其他的存储方式

**Comment by chaishi** [comment]
- 最早期的方式就是远程 DB，后来迁移改成了本地 DB。本地 DB 除了冲突的问题，还有每次都需要提交的问题。
- 已经存在其他的存储方式，json。我后面加一个 json to db 的方式，这样子 DB 冲突了，可以同步你的 json 再次到 db 解决冲突问题（类似现在的测试用例输出）

**Comment by chaishi** [comment]
新增 `npm run api:upload Button` 用于同步 api.json 数据到 DB 文件；
原 `npm run api:download` 表示下载 DB 数据到 api.json。

当发生冲突的时候，.db 文件使用其他人的版本，然后本地执行 `npm run api:upload Button` 同步刚刚修改的组件到 DB，而后便可继续提交。

**Comment by LeeJim** [comment]
感谢 @chaishi 解决了痛点问题
